import { Message, CompleteChatSettingsData, ChatData } from '@/types/chat';

// Helper function to ensure all required properties are present
const ensureMessageProps = (msg: any): Message => ({
  ...msg,
  target_language: msg.target_language || "",
  target_language_text: msg.target_language_text || "",
  english_text: msg.english_text || "",
  translation: msg.translation || "",
  correction_explanation: msg.correction_explanation || "",
  alternative_response: msg.alternative_response || "",
  audio_url: msg.audio_url || "",
  audio_only: msg.audio_only || false,
  highlight_mode: msg.highlight_mode || "off"
});

export const mockChatSettings: CompleteChatSettingsData = {
  id: 1,
  language: 'english',
  language_code: 'en',
  mode: 'chat',
  voice: 'alloy',
  voice_provider: 'openai',
  speed: 'normal',
  streaming_enabled: true,
  auto_send: false,
  auto_send_threshold: 0.5,
  auto_record: false,
  auto_correct: false,
  auto_translate: 'off',
  topic: '',
  subtopic_category: '',
  topic_category: '',
  client_provider: 'openai',
  model: 'gpt-4',
  transcription_mode: 'realtime',
  ai_model: 'gpt-4',
  dialect_code: 'en',
  avatar_url: '',
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
  highlight_mode: 'off',
  name: 'Test Chat',
  guided_mode: false,
  saved_vocabulary: [],
  translated_vocabulary: [],
  transcription_model: 'whisper-1',
  do_not_ask_questions: false,
  pronunciation_characters: null,
  speed_multiplier: 1.0,
  repeat_corrections: false
};

export const createMockChatSettings = (): CompleteChatSettingsData => ({
  ...mockChatSettings
});

export const createMockChatData = (): ChatData => ({
  ...mockChatData
});

export const mockMessages: Message[] = [
  {
    id: 0,
    role: 'user',
    content: 'Hi',
    target_language: '',
    target_language_text: '',
    english_text: '',
    correction: null,
    translation: '',
    correction_explanation: '',
    alternative_response: '',
    audio_url: '',
    slow_audio_url: null,
    word_timings: [],
    hide_text: false,
    avatar_url: "https://ui-avatars.com/api/?background=c965cc&bold=true&color=ffffff&name=testing+2&size=200",
    chat_message_id: 'test-message-0',
    created_at: new Date().toISOString(),
    audio_only: false,
    highlight_mode: 'off'
  },
  {
    id: 1,
    role: 'assistant',
    content: "In this lesson, you will learn to introduce yourself, including name, age, nationality, city of residence, and occupation. You will also learn how to ask questions back, including using 'and you?' for a natural flow.\n\nRemember, you can use English when you don't know how to say something in Japanese.\n\nLet's start with asking someone's name:\n\"What is your name?\" in Japanese is:\n\"Onamae wa nan desu ka?\"\n\nPlease repeat that phrase.",
    target_language: '',
    target_language_text: '',
    english_text: '',
    correction: null,
    translation: '',
    correction_explanation: '',
    alternative_response: '',
    audio_url: '',
    slow_audio_url: null,
    word_timings: [],
    hide_text: false,
    avatar_url: "https://cdn.languastream.com/Avatars/m21.jpg",
    chat_message_id: 'test-message-1',
    created_at: new Date().toISOString(),
    audio_only: false,
    highlight_mode: 'off'
  },
  {
    id: 2,
    role: 'user',
    content: 'Hi',
    target_language: '',
    target_language_text: '',
    english_text: '',
    correction: null,
    translation: '',
    correction_explanation: '',
    alternative_response: '',
    audio_url: '',
    slow_audio_url: null,
    word_timings: [],
    hide_text: false,
    avatar_url: "https://ui-avatars.com/api/?background=c965cc&bold=true&color=ffffff&name=testing+2&size=200",
    chat_message_id: 'test-message-2',
    created_at: new Date().toISOString(),
    audio_only: false,
    highlight_mode: 'off'
  },
  {
    id: 3,
    role: 'assistant',
    content: "Let me start over with just the first and most basic greeting:\n\nTo say \"Hello\" in Japanese, say:\n\"Konnichiwa\"\n\nPlease repeat that.",
    target_language: '',
    target_language_text: '',
    english_text: '',
    correction: null,
    translation: '',
    correction_explanation: '',
    alternative_response: '',
    audio_url: '',
    slow_audio_url: null,
    word_timings: [],
    hide_text: false,
    avatar_url: "https://cdn.languastream.com/Avatars/m21.jpg",
    chat_message_id: 'test-message-3',
    created_at: new Date().toISOString(),
    audio_only: false,
    highlight_mode: 'off'
  },
  {
    id: 4,
    role: 'user',
    content: 'Hi',
    target_language: '',
    target_language_text: '',
    english_text: '',
    correction: null,
    translation: '',
    correction_explanation: '',
    alternative_response: '',
    audio_url: '',
    slow_audio_url: null,
    word_timings: [],
    hide_text: false,
    avatar_url: "https://ui-avatars.com/api/?background=c965cc&bold=true&color=ffffff&name=testing+2&size=200",
    chat_message_id: 'test-message-4',
    created_at: new Date().toISOString(),
    audio_only: false,
    highlight_mode: 'off'
  },
  {
    id: 5,
    role: 'assistant',
    content: "Let me try one more time, even simpler:\n\nTo say \"Hi\" in Japanese, say:\n\"Hai\"\n\nPlease repeat that.",
    target_language: '',
    target_language_text: '',
    english_text: '',
    correction: null,
    translation: '',
    correction_explanation: '',
    alternative_response: '',
    audio_url: '',
    slow_audio_url: null,
    word_timings: [],
    hide_text: false,
    avatar_url: "https://cdn.languastream.com/Avatars/m21.jpg",
    chat_message_id: 'test-message-5',
    created_at: new Date().toISOString(),
    audio_only: false,
    highlight_mode: 'off'
  },
  {
    id: 6,
    role: 'user',
    content: 'Hi',
    target_language: '',
    target_language_text: '',
    english_text: '',
    correction: null,
    translation: '',
    correction_explanation: '',
    alternative_response: '',
    audio_url: '',
    slow_audio_url: null,
    word_timings: [],
    hide_text: false,
    avatar_url: "https://ui-avatars.com/api/?background=c965cc&bold=true&color=ffffff&name=testing+2&size=200",
    chat_message_id: 'test-message-6',
    created_at: new Date().toISOString(),
    audio_only: false,
    highlight_mode: 'off'
  },
  {
    id: 7,
    role: 'assistant',
    content: "Let me try one more time, even simpler:\n\nTo say \"Hi\" in Japanese, say:\n\"Hai\"\n\nPlease repeat that.",
    target_language: '',
    target_language_text: '',
    english_text: '',
    correction: null,
    translation: '',
    correction_explanation: '',
    alternative_response: '',
    audio_url: '',
    slow_audio_url: null,
    word_timings: [],
    hide_text: false,
    avatar_url: "https://cdn.languastream.com/Avatars/m21.jpg",
    chat_message_id: 'test-message-7',
    created_at: new Date().toISOString(),
    audio_only: false,
    highlight_mode: 'off'
  },
  {
    id: 8,
    role: 'user',
    content: 'Hi',
    target_language: '',
    target_language_text: '',
    english_text: '',
    correction: null,
    translation: '',
    correction_explanation: '',
    alternative_response: '',
    audio_url: '',
    slow_audio_url: null,
    word_timings: [],
    hide_text: false,
    avatar_url: "https://ui-avatars.com/api/?background=c965cc&bold=true&color=ffffff&name=testing+2&size=200",
    chat_message_id: 'test-message-8',
    created_at: new Date().toISOString(),
    audio_only: false,
    highlight_mode: 'off'
  },
  {
    id: 9,
    role: 'assistant',
    content: "I notice you're only saying \"Hi\". For this Japanese lesson to work, I need you to actively participate by repeating the phrases I teach you.\n\nCould you please confirm if you're ready to learn by saying \"yes\" or \"no\"?",
    target_language: '',
    target_language_text: '',
    english_text: '',
    correction: null,
    translation: '',
    correction_explanation: '',
    alternative_response: '',
    audio_url: '',
    slow_audio_url: null,
    word_timings: [],
    hide_text: false,
    avatar_url: "https://cdn.languastream.com/Avatars/m21.jpg",
    chat_message_id: 'test-message-9',
    created_at: new Date().toISOString(),
    audio_only: false,
    highlight_mode: 'off'
  }
];

export const mockChatData: ChatData = {
    chat: mockChatSettings,
    messages: mockMessages.map(ensureMessageProps),
    user: {
      id: 1,
      name: 'Test User',
      avatar_url: ''
    },
    message_limit_reached: false,
    chat_form_options: {
      mode_options: {},
      voice_options: {},
      ai_model_options: [],
      transcription_mode_options: [],
      speed_options: [],
      pronunciation_options: [],
      transcription_model_options: {}
    }
  };

  export const mockChatDataNoMessages: ChatData = {
    chat: mockChatSettings,
    messages: [],
    user: {
      id: 1,
      name: 'Test User',
      avatar_url: ''
    },
    message_limit_reached: false,
    chat_form_options: {
      mode_options: {},
      voice_options: {},
      ai_model_options: [],
      transcription_mode_options: [],
      speed_options: [],
      pronunciation_options: [],
      transcription_model_options: {}
    }
  };
  